---
title: "UN Voting Cluster Analysis"
author: "Erin Lemons (eml129), Kenton Thibault (akt44), Bria Pullin (bnp21)"
date: "12/07/2021"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango
editor_options: 
  chunk_output_type: console
---

<style> body {text-align: justify} </style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r include = FALSE}
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})

```

```{r library}
library(readr)
library(tidyverse)
library(stringr)
library(haven)
options(scipen = 999)
library(ggthemes)
library(sf)
library(geojsonio)
library(patchwork)
library(lubridate)
library(tidycensus)
library(tidyverse)
library(httr)
library(jsonlite)
library(tidymodels)
library(rpart)
library(rpart.plot)
library(janitor)
library(themis)
library(vip)
library(ranger)
library(factoextra)
library(rjson)
library(mapproj)
library(crsuggest)
```

## Read Data
```{r formatting data and visualizing}
UNvoting <- read_csv("UNVotes.csv")

Africa_ccodes = c("2", "200", "220", "365", "710", "402", "403", "404", "411", "420", "432", "433", "434", "435", "436", "437", "438", "439", "450", "451", "452", "461", "471", "475", "481", "482", "483", "484", "490", "500", "501", "510", "516", "517", "520", "522", "530", "531", "540", "541", "551", "552", "553", "560", "565", "570", "571", "572", "580", "581", "590", "591", "600", "615", "616", "620", "625", "626", "651")

UN_Imp_Votes_Org <- UNvoting %>%
  filter(session==72) %>%
  filter(importantvote==1) %>%
  filter(ccode %in% Africa_ccodes) %>%
  select(resid, ccode, Country, vote) %>%
  mutate(vote=replace(vote, vote==2, 0)) %>%
  mutate(vote=replace(vote, vote==3, -1)) %>%
  mutate(vote=replace(vote, vote==8, 0))

UN_Imp_Votes <- UN_Imp_Votes_Org %>%
  pivot_wider(names_from=resid, values_from=vote)
```

## PCA
```{r models}
UN_Imp_Votes[1:6, 1:6]
UN_Imp_Votes_1 <- UN_Imp_Votes %>%
  na.omit() %>%
  select(-ccode)

UN_Numeric <- UN_Imp_Votes_1 %>%
  select_if(is.numeric)

UN_pca <- prcomp(UN_Numeric)

UN_pcs <- UN_pca %>%
  .$x %>%
  as_tibble()

UN_pcs <- bind_cols(
  select(UN_Imp_Votes_1, Country),
  UN_pcs
)

summary(UN_pca)
```
## Cluster Analysis
```{r estimation}
fviz_nbclust(UN_Numeric, FUN = kmeans, method = "wss")
fviz_nbclust(UN_Numeric, FUN = kmeans, method = "silhouette")
fviz_nbclust(UN_Numeric, FUN = kmeans, method = "gap_stat")

UN_kmeans3 <- kmeans(UN_Numeric, centers = 3, 
                     nstart = 100)

UN_clusters <- bind_cols(
  select(UN_Imp_Votes_1, Country),
select(UN_pcs, PC1, PC2),
cluster3 = UN_kmeans3$cluster)

mpowers <- c("USA", "GBR", "FRA", "CHN", "RUS")

ggplot() +
  geom_point(data = UN_clusters, 
             aes(PC1, PC2, 
                 color = factor(cluster3)),
             alpha = 0.5) +
  geom_text(data = filter(UN_pcs, Country %in% mpowers),
            aes(PC1, PC2, label = Country)) +
  scale_color_manual(values = c("blue", "red", "yellow")) +
  labs(title = "K-Means with K=3 and PCA",
       x = "PC1 (0.35 of Variation)",
       y = "PC2 (0.26 of Variation)") +
  theme_minimal() +
  guides(text = NULL)
```

## Map of Clusters

```{r map}

africa_map <- st_read("africa_adm0.geojson")

UN_clusters_africa <- UN_clusters %>%
  filter(Country!= "USA") %>%
  filter(Country!= "RUS") %>%
  filter(Country!= "FRA") %>%
  filter(Country!= "CHN") %>%
  filter(Country!= "GBR")

dim(africa_map)
dim(UN_clusters_africa)

africa_clusters_map <- left_join(africa_map, 
                                 UN_clusters_africa, 
                                 by=c("adm0_a3" = "Country"))
dim(africa_clusters_map)

suggest_top_crs(africa_clusters_map)

africa_clusters_map %>%
  st_transform(crs=5523) %>%
  ggplot() +
  geom_sf(aes(fill = factor(cluster3)))  + 
  scale_fill_manual(values = c("blue", "red", "yellow"),
                    name = "UN Voting Alignment",
                    labels = c("with US, France, Britain", 
                               "with China and Russia", 
                               "Unaligned",
                               "No Information")) +
  geom_sf_text(data = filter(africa_clusters_map, cluster3 == 1),aes(label=name), size=2, fontface="bold") +
  geom_sf_text(data = filter(africa_clusters_map, cluster3 == 2),aes(label=name), size=2, fontface="bold", color="black") +
  labs(title = "Most African Countries Vote Unaligned",
       subtitle = "On 2018 UN General Assembly Votes Deemed Important by US",
       caption = "Data: Erik Voeten's UN Voting Dataset") +
  theme_void()
  
```